version: "3.9"
services:
  postgres:
    image: postgres:14.2
    container_name: postgres_link_converter_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=link_converter
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
  redis:
    image: redis:6.2.6
    container_name: redis_link_converter_container
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
  link_converter:
    build:
      context: .
      dockerfile: Dockerfile-local
    container_name: link_converter_container
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: dev

volumes:
  pg_data:
