spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password: ""
    timeout: 60000
  data:
    mongodb:
      database: LinkConverterDb
      host: localhost
      port: 27017
server:
  error:
    include-stacktrace: never
