spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password: ""
    timeout: 60000
  datasource:
    url: jdbc:postgresql://localhost:5432/link_converter?useUnicode=true&characterEncoding=utf-8
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update

server:
  error:
    include-stacktrace: never

query-mappings:
  optional-params:
    boutiqueId: CampaignId
    merchantId: MerchantId

management:
  endpoint:
    health:
      group:
        connections:
          include:
            - db
            - redis
          show-details: always